### ISSUE TITLE
Use variable media queries breakpoints

### ISSUE THREAD

**Issue by c10b10** [tachyons-css/tachyons-flexbox#6]
In the tachyons you define custom breakpoints "--breakpoint-medium", why not use those breakpoints in this component as well?

**Comment by mrmrs** [comment]
We do use the same ones here as well. If you look at the top of this file we define the media queries in the same way as in the main tachyons repo https://github.com/tachyons-css/tachyons-flexbox/blob/master/src/tachyons-flexbox.css

Let me know if I am not understanding your question correctly.
