### ISSUE TITLE
How to get equal columns

### ISSUE THREAD

**Issue by ArthurClemens** [tachyons-css/tachyons-flexbox#7]
Using T classes, I am not able to get equal columns. Using CSS I would write for adjacent containers:

```
div {
    flex: 1 0;
}
```
To enable growing but not shrinking.

See this fiddle (with Tachyon classes and an example with an extra style): https://jsfiddle.net/ArthurClemens/5b9nLpu2/

**Comment by mrkhdly** [comment]
Tachyons v5 will become a monorepo so this issue is being closed, if the issue is still relevant please open an issue with the main repo https://github.com/tachyons-css/tachyons/issues/new & link to this one
