### ISSUE TITLE
Avoid old CSS flexbox (PWA, Google Lighthouse)

### ISSUE THREAD

**Issue by sebastienbarre** [tachyons-css/tachyons-flexbox#9]
Howdy. 
I'm running [Google Lighthouse](https://github.com/GoogleChrome/lighthouse) to audit my app against Progressive Web Apps best practices, and I'm getting some warnings.

```
Avoids old CSS flexbox 
The 2009 spec of Flexbox is deprecated and is 2.3x slower than the latest spec
.flex {
  display:-webkit-box;
}
 .flex-m {
  display:-ms-flexbox;
}
etc.
```
See [Flexbox layout isn't slow](https://developers.google.com/web/updates/2013/10/Flexbox-layout-isn-t-slow) for Old v New Flexbox Benchmark.
See: [Site Does Not Use The Old CSS Flexbox](https://developers.google.com/web/tools/lighthouse/audits/old-flexbox)

### How to pass the audit

Under URLs, Lighthouse lists every instance of `display: box` that it found on your page's stylesheets. Replace every instance with the new syntax, `display: flex`.

If a stylesheet is using `display: box`, then it may be using other deprecated Flexbox properties. In short, every property that begins with box, such as `box-flex`, is deprecated and should be replaced. See [CSS Flexbox 2009/2011 Spec Syntax Property Mapping](https://wiki.csswg.org/spec/flexbox-2009-2011-spec-property-mapping) to see exactly how the old properties map to the new ones.

@mrmrs do you feel strongly about that one?
Thanks

**Comment by sebastienbarre** [comment]
From what I gather in this [`create-react-app` issue](https://github.com/facebookincubator/create-react-app/issues/1658#issuecomment-282609229) you may need to pass the `flexbox: 'no-2009'` option to `autoprefixer` in [tachyons-css/tachyons-build-css](https://github.com/tachyons-css/tachyons-build-css).

Or use [luisrudge/postcss-flexbugs-fixes: PostCSS plugin that tries to fix all of flexbug's issues](https://github.com/luisrudge/postcss-flexbugs-fixes), since the build pipeline is already based on PostCSS (see [philipwalton/flexbugs: A community-curated list of flexbox issues and cross-browser workarounds for them.](https://github.com/philipwalton/flexbugs)).

**Comment by mrkhdly** [comment]
Tachyons v5 will become a monorepo so this issue is being closed, if the issue is still relevant please open an issue with the main repo https://github.com/tachyons-css/tachyons/issues/new & link to this one
